### ISSUE TITLE
Install didn't work

### ISSUE THREAD

**Issue by vadi2** [pozemka/cheatsh-qtcreator#26]
I copied the file for my Qt Creator Version, 4.1.2:

```
$ ls ~/.local/share/data/QtProject/qtcreator/plugins
libCheatSh.so
```

But Qt Creator does not see it and it's not listed in the plugins list. What could be wrong?

Thanks for making this!

**Comment by pozemka** [comment]
4.1.2? If it is typo and you actually have Qt Creator 4.12 make sure you create directory 4.12.0 inside ~/.local/share/data/QtProject/qtcreator/plugins. So plugin would be in ~/.local/share/data/QtProject/qtcreator/plugins/4.12.0/libCheatSh.so

**Comment by vadi2** [comment]
Thanks, that worked.
