### ISSUE TITLE
Qt Creator 4.14.0 - plugin is not working

### ISSUE THREAD

**Issue by sourligas** [pozemka/cheatsh-qtcreator#29]
Hi @pozemka ,

I upgraded from QtCreator 4.13 to 4.14 (64-bit Linux) and now the cheatsh plugin is no longer working.

Please check it and find below the error messages from Qt Creator.

Could not resolve dependency 'Core(4.13.0)'
Could not resolve dependency 'TextEditor(4.13.0)'

**Comment by pozemka** [comment]
Hello!
Thank you for your report.
I will update plugin for 4.14 in near time.

**Comment by pozemka** [comment]
@sourligas I've uploaded 4.14 release for Linux. 

Please remove old plugin (libCheatSh.so library) and unpack new one to .local/share/data/QtProject/qtcreator/plugins.
Full path should be something like `/home/user/.local/share/data/QtProject/qtcreator/plugins/4.14.0/libCheatSh.so`

Please let me know if it working?

I've only checked it on OpenSuse and build environment has changed from the last build too.

**Comment by sourligas** [comment]
@pozemka I checked it earlier on Qt Creator 4.14.0 Linux Mint 19.3 64-bit and it works fine!

Tomorrow I could make a second check on Qt Creator 4.14.0  Ubuntu 18.04 64-bit and let you know about that.

Thank you for your quick response!

**Comment by sourligas** [comment]
@pozemka it also works fine on Qt Creator 4.14.0 Ubuntu 18.04 64-bit.

Thanks!

**Comment by pozemka** [comment]
@sourligas thanks for confirming it.
