### ISSUE TITLE
GLIBCXX_3.4.29

### ISSUE THREAD

**Issue by isgursoy** [pozemka/cheatsh-qtcreator#40]
```/opt/qtc/6/lib/qtcreator/plugins/libCheatSh.so: Cannot load library /opt/qtc/6/lib/qtcreator/plugins/libCheatSh.so: (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/qtc/6/lib/qtcreator/plugins/libCheatSh.so))```

QtC 6 run file, prebuilt 2.0.2 release, GCC 10.3.0, Ubuntu 20.04.

**Comment by pozemka** [comment]
@isgursoy Hello. Sorry for delay. 
There was issue with plugin under Ubuntu 20.04. 
I've rebuild plugin using Ubuntu 20.04, QtC 6.0 and Qt 6.2.2. Now it should work.

Linux version of plugin was replaced on the release page https://github.com/pozemka/cheatsh-qtcreator/releases/tag/2.0.2 


![image](https://user-images.githubusercontent.com/1259724/147387160-c8b8c90c-941f-4102-92b3-710b0003a933.png)

**Comment by isgursoy** [comment]
Great, I just wanted to let you know, I have already compiled mine from sources.
